forum_app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from forum_app.views.post_views import post, post_2
from forum_app.views.post_views import PostView, PostCreateView, PostEditView, PostDeleteView
from forum_app.views.account_views import LogInView, LogOutView, SignUpView, InitProfileView, EditProfileView, ShowProfileView

app_name = 'forum_app'

urlpatterns = [
    path('', PostView.as_view(), name='home'),
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('registration/', SignUpView.as_view(), name='registration'),
    path('post/<int:post_id>/', post, name='post'),
    path('post/<int:post_id>/<int:com_id>/', post_2, name='post_2'),
    path('post_create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:post_id>/edit/', PostEditView.as_view(), name='post_edit'),
    path('post/<int:post_id>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('profile/init/', InitProfileView.as_view(), name='profile_init'),
    path('profile/<int:profile_id>/edit/', EditProfileView.as_view(), name='profile_edit'),
    path('profile/<int:profile_id>/show/', ShowProfileView.as_view(), name='profile_show'),
]

rush01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum_app/models/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
	title = models.CharField(max_length=64)
	author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	content = models.TextField()
	created = models.DateTimeField()

	def __str__(self):
		return self.title

class Comment(models.Model):
	post = models.ForeignKey('Post', on_delete=models.CASCADE, null=True)
	parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, related_name='child_comment')
	author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	content = models.TextField()
	created = models.DateTimeField()

	def __str__(self):
		return self.content

forum_app/models/profile_models.py
from django.contrib.auth.forms import UsernameField
from django.db import models
from django.contrib.auth.models import User
from django.db.models import TextField, EmailField, CharField, ImageField
from django.db.models.fields import BooleanField

class Profile(models.Model):
    user = models.ForeignKey(User, related_name='profile', on_delete=models.CASCADE)
    name = models.CharField(max_length=64, null=True)
    surname = models.CharField(max_length=64, null=True)
    email = models.EmailField(max_length=64, null=True)
    description = models.TextField(max_length=128, blank=True)
    image = models.ImageField(blank=True, null=False)

    def __str__(self):
            return str(self.user)

forum_app/forms/account_forms.py
from django.db.models import TextField
from django.contrib.auth.models import User
from django.db.models.fields import CharField
from django.db.models import ImageField
from django.forms.models import ModelForm
from forum_app.models.profile_models import Profile
from django import forms

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name','surname','email', 'description', 'image']

forum_app/forms/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from forum_app.models.models import Post, Comment


class PostForm(ModelForm):
	class Meta:
		model = Post
		# fields = ['title', 'author', 'content', 'created']
		fields = ['title', 'content']

class CommentForm(ModelForm):
	class Meta:
		model = Comment
		# fields = ['post', 'author', 'content', 'created']
		fields = ['content']

forum_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from .forms import UserForm, PostForm, CommentForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

def home(request):
	user_name = 'Guest'
	user = ''

	post_list = Post.objects.order_by('-created')
	context = {'post_list':post_list, 'user_name':user_name, 'user':user}

	return render(request, 'home.html', context)

def registration(request):
	user_name = 'Guest'

	if request.method == 'POST':
		form = UserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			user_name = request.POST.get('username')
			return redirect('/')
		messages.error(request, "Unsuccessful registration. Invalid information.")
	else:
		form = UserForm()
	return render(request, 'registration.html', {'user_name':user_name, 'form':form})

def login_request(request):
	user_name = 'Guest'
	username = ''
	notice = ''

	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				user_name = request.POST.get('username')
				return redirect('/')
			else:
				messages.error(request, "Invalid username or password.")
		else:
			messages.error(request, "Invalid username or password.")
	else:
		form = UserForm()

	return render(request, 'login.html', {'user_name':user_name, 'form':form, 'notice':notice})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect('/')

def post(request, post_id):
	post =  get_object_or_404(Post, id=post_id)
	context = {'post':post}
	return render(request, 'post.html', context)

forum_app/views/account_views.py
from django.db.models.query import QuerySet
from django.http.response import HttpResponse
from django.shortcuts import redirect, render, reverse
from django.views.decorators.csrf import csrf_exempt
import forum_app
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.views.generic import FormView, CreateView, ListView, RedirectView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from forum_app.models.profile_models import Profile
from forum_app.forms.account_forms import ProfileForm
from django.contrib import messages
from django.views.generic.base import View

# class LogInView(FormView):
# @login_required(redirect_field_name=None)
# class LogInView(LoginView):
#     template_name = 'login.html'
#     form_class = AuthenticationForm
#     redirect_field_name = next
#     pattern_name = reverse_lazy('forum_app:home')
#     login_url = reverse_lazy('forum_app:login')
class LogInView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('forum_app:home')
        form = AuthenticationForm()
        return render(request, 'login.html', {'form' : form })

    def post(self, request):
        if request.user.is_authenticated:
            redirect('forum_app:home')
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('forum_app:home')
        else:
            form = AuthenticationForm()
            return render(request, 'login.html', {'form': form})



class LogOutView(LogoutView):
    def get(self, request):
        logout(request)
        return redirect('forum_app:home')


class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration.html'
    success_url = reverse_lazy('forum_app:home')
    def form_invalid(self, form:UserCreationForm):
        messages.warning(self.request, "Invalid information.")
        return super().form_invalid(form)

class InitProfileView(LoginRequiredMixin,CreateView):
    form_class = ProfileForm
    template_name = 'profile/register.html'
    context_object_name = 'user_profile'
    success_url = reverse_lazy('forum_app:home')
    login_url = reverse_lazy('forum_app:login')
    model = Profile
    queryset = model.objects.all().order_by('-id')
    def form_valid(self, form:ProfileForm):
        profile = form.save(commit=False)
        profile.user = self.request.user
        profile.save()
        return super().form_valid(form)
    def form_invalid(self, form:ProfileForm):
        print(form.errors)
        return super().form_invalid(form)



class EditProfileView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'login'
    model = Profile
    template_name = 'profile/register.html'
    context_object_name = 'user_profile'
    fields = ['name', 'surname', 'email', 'description', 'image']
    # success_url = reverse_lazy('forum_app:profile_show', kwargs={'profile_id':model.pk})
    pk_url_kwarg = 'profile_id'

    def get_success_url(self):
        return reverse('forum_app:profile_show', kwargs={'profile_id':self.object.id})

class ShowProfileView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profile/profile.html'
    context_object_name = 'user_profile'
    login_url = reverse_lazy('forum_app:login')
    success_url = reverse_lazy('forum_app:home')
    def get_queryset(self):
        profile = Profile.objects.filter(user = self.request.user)
        return profile

forum_app/views/post_views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from forum_app.forms.forms import PostForm, CommentForm
from forum_app.models.models import Post, Comment
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, reverse
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# from forum_app.models import Post


class PostView(LoginRequiredMixin, ListView):
	login_url = '/login/'
	redirect_field_name = 'login'
	model = Post
	template_name = 'home.html'
	paginate_by = 10
	context_object_name = 'post_list'

	def get_queryset(self):
		post_list = Post.objects.order_by('-created')
		# page_number = int(self.request.GET.get('p',1))
		# paginator = Paginator(post_list, 5)
		# page_obj = paginator.get_page(page_number)
		return post_list

class PostCreateView(LoginRequiredMixin, CreateView):
	login_url = '/login/'
	redirect_field_name = 'login'
	model = Post
	template_name = 'post_edit.html'
	fields = ['title', 'content']
	context_object_name = 'form'

	def form_valid(self, form):
		post = form.save(commit=False)
		post.author = self.request.user
		post.created = timezone.now()
		post.save()
		return redirect('/')

class PostEditView(LoginRequiredMixin, UpdateView):
	login_url = '/login/'
	redirect_field_name = 'login'
	model = Post
	template_name = 'post_edit.html'
	fields = ['title', 'content']
	context_object_name = 'form'
	pk_url_kwarg = 'post_id'

	def get_success_url(self):
		return reverse('forum_app:post', kwargs={'post_id':self.object.id})

class PostDeleteView(LoginRequiredMixin, DeleteView):
	login_url = '/login/'
	redirect_field_name = 'login'
	model = Post
	template_name = 'post_delete.html'
	context_object_name = 'post'
	pk_url_kwarg = 'post_id'

	def get_success_url(self):
		return reverse('forum_app:home')

# class CommentDeleteView(LoginRequiredMixin, DeleteView):
# 	login_url = '/login/'
# 	redirect_field_name = 'login'
# 	model = Comment
# 	template_name = 'comment_delete.html'
# 	context_object_name = 'comment'
# 	pk_url_kwarg = 'post_id'

# 	def get_success_url(self):
# 		return reverse('forum_app:post', kwargs={'post_id':self.object.id})

@login_required(login_url='forum_app:login')
def post(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	print(post)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			form_tmp = form.save(commit=False)
			form_tmp.post = post
			form_tmp.author = request.user
			form_tmp.created = timezone.now()
			form_tmp.save()
			form = form_tmp
			context = {'post':post, 'form':form}
			return redirect('/post/' + str(post_id))
	else:
		form = CommentForm()
	context = {'post':post, 'form':form}
	return render(request, 'post.html', context)

@login_required(login_url='forum_app:login')
def post_2(request, post_id, com_id):
	post = get_object_or_404(Post, pk=post_id)
	comment = get_object_or_404(Comment, pk=com_id)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			form_tmp = form.save(commit=False)
			# form_tmp.post = post
			form_tmp.parent_comment = comment
			form_tmp.author = request.user
			form_tmp.created = timezone.now()
			form_tmp.save()
			form = form_tmp
			context = {'post':post, 'form':form}
			return redirect('/post/' + str(post_id))
	else:
		form = CommentForm()
	context = {'post':post, 'form':form, 'com':comment}
	return render(request, 'post_2.html', context)

forum_app/views/views.py
# from django.shortcuts import render, redirect
# from forum_app.models.models import Post
# from forum_app.forms import UserForm, PostForm, CommentForm


# from django.contrib.auth import login, logout, authenticate
# from django.contrib import messages
# from django.contrib.auth.forms import AuthenticationForm


# def home(request):
# 	user_name = 'Guest'
# 	user = ''

# 	post_list = Post.objects.order_by('-created')
# 	context = {'post_list':post_list, 'user_name':user_name, 'user':user}

# 	return render(request, 'home.html', context)

# def registration(request):
# 	user_name = 'Guest'

# 	if request.method == 'POST':
# 		form = UserForm(request.POST)
# 		if form.is_valid():
# 			user = form.save()
# 			login(request, user)
# 			user_name = request.POST.get('username')
# 			return redirect('/')
# 		messages.error(request, "Unsuccessful registration. Invalid information.")
# 	else:
# 		form = UserForm()
# 	return render(request, 'registration.html', {'user_name':user_name, 'form':form})

# def login_request(request):
# 	user_name = 'Guest'
# 	username = ''
# 	notice = ''

# 	if request.method == "POST":
# 		form = AuthenticationForm(request, data=request.POST)
# 		if form.is_valid():
# 			username = form.cleaned_data.get('username')
# 			password = form.cleaned_data.get('password')
# 			user = authenticate(username=username, password=password)
# 			if user is not None:
# 				login(request, user)
# 				messages.info(request, f"You are now logged in as {username}.")
# 				user_name = request.POST.get('username')
# 				return redirect('/')
# 			else:
# 				messages.error(request, "Invalid username or password.")
# 		else:
# 			messages.error(request, "Invalid username or password.")
# 	else:
# 		form = UserForm()

# 	return render(request, 'login.html', {'user_name':user_name, 'form':form, 'notice':notice})

# def logout_request(request):
# 	logout(request)
# 	messages.info(request, "You have successfully logged out.")
# 	return redirect('/')

forum_app/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
        {% block title %}
        {% endblock title %}
      </title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    {% bootstrap_messages %}
    <div class="container">
    <hr class="my-3">
      {% include "nav.html" %}
      {% block content %}
      {% endblock content%}
    </div>
  </body>
</html>

forum_app/templates/comment.html
{% load django_bootstrap5 %}
{% for child_com in comment.child_comment.all %}
  <div>{% include "comment_space.html" %}|&nbsp;&nbsp;{{ child_com.author }} | {{ child_com.created }}</div>
  <div>{% include "comment_space.html" %} > {{ child_com.content }}
  <a class="btn btn-outline-success btn-sm" href={% url 'forum_app:post_2' post.id child_com.id %}>comment</a>
  {% if com.id == child_com.id %}
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button "Save" button_type="submit" button_class="btn btn-outline-success btn-sm" %}
      <a class="btn btn-outline-success btn-sm" href={% url 'forum_app:post' post.id %}>cancel</a>
    </form>
  {% endif %}
  </div>
  {% with child_com as comment %}
    {% if comment.child_comment.all %}
      {% include 'comment.html' %}
    {% endif %}
  {% endwith %}
{% endfor %}

forum_app/templates/comment_space.html
{% if comment.parent_comment %}
|&nbsp;&nbsp;
{% endif %}
{% with comment.parent_comment as comment %}
  {% if comment.parent_comment %}
    {% include 'comment_space.html' %}
  {% endif %}
{% endwith %}

forum_app/templates/home.html
{% extends "base.html" %}
{% block title %}
Rush01
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <a button_type="link" class="btn btn-outline-secondary btn-sm" href={% url 'forum_app:post_create' %}>create</a>
{% endif %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Created</th>
    </tr>
  </thead>
  <tbody>
    {% for post in post_list %}
      <tr>
        <th scope="row">{{post.id}}</th>
        {% if user.is_authenticated %}
          <td><a href={% url 'forum_app:post' post.id %}>{{ post.title }}</a></td>
        {% else %}
          <td>{{ post.title }}</td>
        {% endif %}
        <td>{{ post.author }}</td>
        <td>{{ post.created }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item">
      {% if page_obj.has_previous %}
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span></a>
      {% else %}
        <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span></a>
      {% endif %}
    </li>
  {% for page_number in paginator.page_range%}
    {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
      {% if page_number == page_obj.number %}
        <li class="page-item active"><a class="page-link" href="?page={{ page_number }}">{{page_number}}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{page_number}}</a></li>
      {% endif %}
    {% endif %}
  {% endfor %}
    <li class="page-item">
      {% if page_obj.has_next %}
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&raquo;</span></a>
      {% else %}
        <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&raquo;</span></a>
      {% endif %}
    </li>
  </ul>
</nav>

{% endblock %}

forum_app/templates/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
Login
{% endblock %}

{% block content %}

<form action="{% url 'forum_app:login' %}" method="post">
  {% if notice %}
    <p>{{ notice }}</p>
  {% endif %}
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button "login" button_type="submit" button_class="btn-success" %}
  {% bootstrap_button "reset" button_type="reset" button_class="btn btn-outline-success" %}
</form>
{% endblock %}

forum_app/templates/nav.html
{% load django_bootstrap5 %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a href="{% url 'forum_app:home' %}" class="navbar-brand">42_Django_Forum</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% if user.is_authenticated %}
            {% if user.profile.all.0 %}
              <a href="{% url 'forum_app:profile_show' user.profile.all.0.id%}" class="nav-link" >profile_show</a>
            {% else %}
              <a href="{% url 'forum_app:profile_init'%}" class="nav-link" >profile_init</a>
            {% endif %}
          {% else %}
            <a href="{% url 'forum_app:registration' %}" class="nav-link" >registration</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a href="{% url 'forum_app:logout' %}" class="nav-link" >logout</a>
          {% else %}
            <a href="{% url 'forum_app:login' %}" class="nav-link active" >login</a>
          {% endif %}
        </li>
      </ul>
      <span class="navbar-text">** hello {{user}}**</span>
    </div>
  </div>
</nav>

forum_app/templates/post.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
Rush01
{% endblock %}

{% block content %}
  <br>
  <div> {{ post.title }} <div>
  <div> {{ post.author }} | {{ post.created }}
  <a button_type="link" class="btn btn-outline-secondary btn-sm" href={% url 'forum_app:home' %}>Back to Home</a>
  {% if post.author == user %}
    <a button_type="link" class="btn btn-outline-secondary btn-sm" href={% url 'forum_app:post_edit' post.id %}>Edit Post</a>
    <a button_type="link" class="btn btn-outline-secondary btn-sm" href={% url 'forum_app:post_delete' post.id %}>delete</a>
  {% endif %}</div>
  <br><br>

  <h5>content</h5>
  <p class="text-md-start">{{ post.content }}</p>
  <br><br>

  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "Save" button_type="submit" button_class="btn btn-outline-success btn-sm" %}
  </form>
  <br><br>

  {% for comment in post.comment_set.all %}
    <div>{% include "comment_space.html" %}{{ comment.author }} | {{ comment.created }}</div>
    <div>{% include "comment_space.html" %}{{ comment.content }}
    <a class="btn btn-outline-success btn-sm" href={% url 'forum_app:post_2' post.id comment.id %}>comment</a>
    </div>
    {% if comment.child_comment.all %}
      {% include 'comment.html' %}
    {% endif %}
  {% endfor %}

{% endblock %}

forum_app/templates/post_2.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
Rush01
{% endblock %}

{% block content %}

  <br>
  <div> {{ post.title }} <div>
  <div> {{ post.author }} | {{ post.created }}
  <a button_type="link" class="btn btn-outline-secondary btn-sm" href={% url 'forum_app:home' %}>Back to Home</a>
  {% if post.author == user %}
    <a button_type="link" class="btn btn-outline-secondary btn-sm" href={% url 'forum_app:post_edit' post.id %}>Edit Post</a>
    <a button_type="link" class="btn btn-outline-secondary btn-sm" href={% url 'forum_app:post_delete' post.id %}>delete</a>
  {% endif %}</div>
  <br><br>

  <h5>content</h5>
  <p class="text-md-start">{{ post.content }}</p>
  <br><br>

  {% for comment in post.comment_set.all %}
    {% if not comment.parent_comment %}
      <div>{% include "comment_space.html" %}{{ comment.author }} | {{ comment.created }}</div>
      <div>{% include "comment_space.html" %}{{ comment.content }}
      <a class="btn btn-outline-success btn-sm" href={% url 'forum_app:post_2' post.id comment.id %}>comment</a>
      {% if com.id == comment.id %}
        <form method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button "Save" button_type="submit" button_class="btn btn-outline-success btn-sm" %}
          <a class="btn btn-outline-success btn-sm" href={% url 'forum_app:post' post.id %}>cancel</a>
        </form>
      {% endif %}
      </div>
    {% endif %}
    {% if comment.child_comment.all %}
      {% include 'comment.html' %}
    {% endif %}
  {% endfor %}

{% endblock %}

forum_app/templates/post_delete.html
{% extends "base.html" %}

{% block title %}
Rush01
{% endblock %}

{% block content %}
  {% if user == post.author %}
    <form method="POST">
      {% csrf_token %}
      <div>삭제하시겠습니까?</div>
      <input type="submit" value="Delete">
    </form>
  {% else %}
    <div>접근권한이 없습니다.</div>
  {% endif %}

{% endblock %}

forum_app/templates/post_edit.html
{% extends "base.html" %}
{% load django_bootstrap5 %}s
{% block title %}
Rush01
{% endblock %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button "Save" button_type="submit" button_class="btn-success" %}
  <a button_type="link" class="btn btn-outline-success" href="{% url 'forum_app:home' %}" %}>Back</a>
  {% bootstrap_button "reset" button_type="reset" button_class="btn btn-outline-success" %}
</form>

{% endblock %}

forum_app/templates/registration.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
publish
{% endblock %}

{% block content %}

<form action="{%url 'forum_app:registration'%}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button "Registration" button_type="submit" button_class="btn btn-success" %}
  {% bootstrap_button "Cancel" button_type="submit" button_class="btn btn-outline-success" %}
</form>
{% endblock %}